lint-collection: Pin Python versions for ansible-lint
The ansible-lint job with ansible 2.12 fails to install when using the
latest Python version 3.12:

  AttributeError: '_AnsiblePathHookFinder' object has no attribute 'find_spec'

Pin Python to the same versions used in the ansible sanity jobs.

Also pin ansible-lint to 5.* on Python 3.8 since 6+ is not supported.